- name: "Restart/Reload prometheus: testar config file"
  command: "docker run --rm -it -v {{ prometheus_base_dir }}/config/prometheus.yml:/etc/prometheus/trt3/prometheus.yml:ro -v {{ prometheus_base_dir }}/tls:/etc/prometheus/tls:ro --entrypoint=promtool prom/prometheus:{{ prometheus_version }} check config /etc/prometheus/trt3/prometheus.yml"
  register: prometheus_config_test_handler_result
  listen: 
  - "restart prometheus topic"
  - "reload prometheus topic"

- name: "Restart prometheus: restart do container"
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    restart: yes
    state: started
  listen: "restart prometheus topic"

- name: "Reload prometheus: sighup para o container"
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    state: stopped
    #stop_signal: SIGHUP
    force_kill: yes
    kill_signal: SIGHUP
  listen: "reload prometheus topic"

- name: "Restart nginx: testar config file"
  command: "docker run --rm -it --add-host {{ prometheus_container_name }}:127.0.0.1  -v {{ prometheus_nginx_base_dir }}/config/nginx.conf:/etc/nginx/nginx.conf:ro nginx:{{ prometheus_nginx_version }} nginx -t"
  register: nginx_config_test_handler_result
  listen: "restart nginx topic"

- name: "Restart nginx: restart do container"
  community.docker.docker_container:
    name: "{{ prometheus_nginx_container_name }}"
    restart: yes
    state: started
  listen: "restart nginx topic"
