---

#TODO criar o diretorio, se preciso, antes. Se "aux_uses_lvm" for false e o base_dir
#     não existir, teremos erro.

#
# NOTA: Estou deixando esta "preparação" para um LV+diretório
#       para "indicar o caminho" se for adotar no futuro algum
#       tipo de caching para o cadvisor (há algumas opções).
#
#       Usar este LV mesmo que o caching seja por redis etc etc
#       (desde que faça sentido usar um diretório, claro)
#

#- name: "Cadvisor mount filesystem from LV"
#  ansible.posix.mount:
#    backup: yes
#    path: "{{ cadvisor_base_dir }}"
#    src: "/dev/{{ vg_data_name }}/cadvisor"
#    fstype: xfs
#    #opts:
#    state: mounted
#  when: aux_uses_lvm
#  tags:
#    - kubetrt3.cadvisor.dirs

#- name: Cadvisor host directories (will later be bound)
#  file:
#    path: "{{ item }}"
#    state: directory
#  loop:
#    - "{{ cadvisor_host_storage_path }}"
#    - "{{ cadvisor_host_auth_path }}"
#  tags:
#    - kubetrt3.cadvisor.dirs

- name: Cadvisor container (pull image)
  community.docker.docker_image:
    name: "{{ cadvisor_image }}"
    tag: "{{ cadvisor_version }}"
    state: present
    source: pull
  ignore_errors: "{{ ansible_check_mode }}"    
  tags: 
    - kubetrt3.cadvisor.pull.image
    - kubetrt3.cadvisor.update

- name: Cadvisor start up
  community.docker.docker_container:
    name: "{{ cadvisor_container_name }}"
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: yes
    read_only: no
    memory: 0
    # afetava: auto_remove, detach, init, interactive, memory, paused, privileged, read_only and tty options.
    container_default_behavior: no_defaults    
    image: "{{ cadvisor_image }}:{{ cadvisor_version }}"
    state: started
    recreate: yes
    restart: no
    network_mode: "{{ 'bridge' if aux_docker_network_name is not defined else aux_docker_network_name }}"
    networks:
      - name: "{{ 'bridge' if aux_docker_network_name is not defined else aux_docker_network_name }}"
    networks_cli_compatible: yes
    restart_policy: "always"
    command:
      - "-url_base_prefix"
      - "{{ cadvisor_path_prefix }}"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro" 
      - "/var/lib/docker/:/var/lib/docker:ro" 
      - "/dev/disk/:/dev/disk:ro" 
    devices:
      - "/dev/kmsg" 
    exposed_ports: "{{ cadvisor_container_ports }}"
    ports: "{{ cadvisor_container_port_mappings }}"
    labels: "{{ cadvisor_container_labels }}"
    env: "{{ cadvisor_container_envs }}"
  ignore_errors: "{{ ansible_check_mode }}"        
  tags:
    - kubetrt3.cadvisor.start
    - kubetrt3.cadvisor.update
...
